### ISSUE TITLE
Getting Started, Community, Contribute - Project website doc edits

### ISSUE THREAD

**Issue by juliana-hsu** [open-cluster-management-io/open-cluster-management-io.github.io#114]
Quick Start

Deploy a klusterlet agent on your _managed_ cluster

Accept join request and verify
2. <remove We would get a>  _Result_ looks like the following after csr created:
4. Verify managedcluster _has_ been created successfully:

Bootstrap via Operatorhub.io
Install and create a Klusterlet agent on your _managed_ cluster.

Klusterlet agent

What is next
If the managed cluster status is not _true_, refer to Troubleshooting to debug on your cluster.

Troubleshooting
The managed cluster status is not _true._
For example, _the result below is shown when_ checking managedcluster <remove and get below result>.
You can use <remove below> _the_ commands _below_ to get more debug info. If the provided info <remove can’t> _doesn't_ help, please log an issue to us.

If the policy framework depends on Application lifecycle management then maybe that should listed first in the left nav?

Policy framework

Architecture
Need more explanation about the Policy Architecture.  The diagram isn't self explanatory.  If the info is in the git README let's point to that.

Install from prebuilt images on Quay.io
2. Ensure the pods are running on _the_ hub with the following command:

https://github.com/open-cluster-management/policy-collection
- Can 'stable' policies be used by the upstream community code?  It only says they can be used by the RHACM product.

Application lifecycle management

Need more of an explanation on the architecture and how the components are useful.

Community

Releases
- v0.4.0 - July 2021
- v0.5.0 - October 2021

Resources
Is the open-cluster-management, Github links correct?  I see midstream repos?

Contribute
Is the repository link correct?  I see midstream repos?

https://github.com/open-cluster-management-io/community/blob/main/MISSION.md
- Need to remove the sentence about Observability, and there may be other parts of the sentences that are not relevant 
- Remove sentence about API for health metrics

https://github.com/open-cluster-management-io/community#community-meetings
Website link appears wrong?
Community meetings link doesn't do anything?

**Comment by qiujian16** [comment]
I think we are done on this
