### ISSUE TITLE
[Question] Can "Quick Start" part cover the "Core Components" steps?

### ISSUE THREAD

**Issue by xq2005** [open-cluster-management-io/open-cluster-management-io.github.io#128]
I followed the Quick Start to install `cluster manager` on hub cluster and `klusterlet` on managed cluster, all works fine. There is no need to install these 2 core components manually. Is it right?

Cluster manager: https://open-cluster-management.io/getting-started/core/cluster-manager/ 
Klusterlet agent: https://open-cluster-management.io/getting-started/core/register-cluster/

**Comment by mikeshng** [comment]
Yes, you are right.

"Install using clusteradm" should be an option in both cluster manager and register cluster page (as well as the app manager page).

**Comment by mikeshng** [comment]
@xq2005 FYI to install app addon using `clusteradm` follow
https://github.com/open-cluster-management-io/clusteradm#install-addons
and then
https://github.com/open-cluster-management-io/clusteradm#enable-addons

**Comment by xq2005** [comment]
@mikeshng Thanks for you quick response. 

`clusteradm` can install all components in OCM. "Quick Start" has the same level with "Core Components" and "Add-ons and Integrations". It makes me confusing before checking resources under OCM's namespaces. 

Will the doc update with the latest `clusteradm` capability?

**Comment by mikeshng** [comment]
@xq2005 Yes, we will update the doc. Just to clarify `clusteradm` can only handle application-manager addon for now but not the policy pieces.

You can also open a PR with your recommended changes as well :) 
It will be a good first issue if you want to be hands on with our community :)

**Comment by xq2005** [comment]
@mikeshng Thanks。
