### ISSUE TITLE
[Feature] Looking for markdown Blockquotes support

### ISSUE THREAD

**Issue by yue9944882** [open-cluster-management-io/open-cluster-management-io.github.io#185]
[blackquote](https://www.markdownguide.org/basic-syntax/#blockquotes-1) is will be very useful markdown syntax as "reminders" in our document. e.g.

> NOTE: ....

> WARNING: ...

but currently our website doesnt support the syntax, i presume it's due to the limitations from hugo framework?

**Comment by xuezhaojun** [comment]
/close

This feature request is done after migrated to docsy.
