### ISSUE TITLE
Wrong CRD in scenario "Deploy Kubernetes Resources"

### ISSUE THREAD

**Issue by kalantar** [open-cluster-management-io/open-cluster-management-io.github.io#187]
The prereqs state:

>   - The CRD `AppliedManifestWork` is installed in the managed cluster:
>   
>       ```shell
>       $ kubectl get crd manifestworks.work.open-cluster-management.io 
>       ```

Shouldn't the specified CRD should be `appliedmanifestworks`?

**Comment by mikeshng** [comment]
Thanks for the find. You are right, it should be `appliedmanifestworks.work.open-cluster-management.io` 

Care to submit a PR fix :) ?
