### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by JING21** [open-cluster-management-io/open-cluster-management-io.github.io#206]
There is spelling mistake as I see the homepage of OCM（https://open-cluster-management.io/concepts/architecture/）which is the /en/concepts/architecture.md file. It is misspelling the word  ’declaratively‘ into ’delcaratively‘ at  third row of “Hub-agent” architecture chapter。

**Comment by mikeshng** [comment]
Thank you for reporting this issue.

/assign @mikeshng

**Comment by mikeshng** [comment]
resolves by https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/288
