### ISSUE TITLE
clusteradm instructions specify invalid commands

### ISSUE THREAD

**Issue by mprahl** [open-cluster-management-io/open-cluster-management-io.github.io#208]
I'm using the latest `clusteradm` installed from source and the instructions in the Quick Start mention the `--wait` flag which doesn't exist on both the `init` and `join` commands.

Additionally, in the Application Lifecycle addon installation instructions, the `clusteradm install` command does not exist. I had to follow the directions to install it from source.

**Comment by mikeshng** [comment]
For the app addon I created a PR here to fix the clusteradm doc https://github.com/open-cluster-management-io/clusteradm/pull/118 But I forgot to update the website.

The wait command should exists at least with the `join` command. 
```
$ clusteradm join --help | grep wait
      --wait                             If true, running the cluster registration in foreground.
```
Can you check? Maybe you have another older clusteradm in the path?

**Comment by mprahl** [comment]
@mikeshng thanks!

This is what I get for output:
```bash
~ ❯ clusteradm version                 
client		version	:0.1.0-alpha.4
server release	version	:v1.21.1
~ ❯ clusteradm join --help | grep wait 
      --request-timeout string           The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests. (default "0")
```

**Comment by mprahl** [comment]
@mikeshng you were right. I had the incorrect version installed. Thanks!
