### ISSUE TITLE
Add "Join our Slack" button on the front page next to "Get Started"

### ISSUE THREAD

**Issue by mikeshng** [open-cluster-management-io/open-cluster-management-io.github.io#264]
We have gotten some community feedback regarding it's hard to find the Slack link on our front page. It's currently just a small icon on the top right corner. It's been suggested we add a "Join our Slack" button on the front page next to "Get Started".

What do you think @qiujian16 ?

**Comment by qiujian16** [comment]
yes, I think it sounds good

**Comment by mikeshng** [comment]
/assign mikeshng

I am not an UI expert but I will give it a try first.

**Comment by mikeshng** [comment]
Done.
