### ISSUE TITLE
typo in addon architecture

### ISSUE THREAD

**Issue by cezhang** [open-cluster-management-io/open-cluster-management-io.github.io#287]
<img width="897" alt="addon-architecture" src="https://user-images.githubusercontent.com/5362164/191966542-4ef9f6c5-4213-4cbe-8fff-29c6019aa0ce.png">

Addon-manager in the **Manged cluster** should be Addon-agent?

**Comment by mikeshng** [comment]
Thank you for reporting this issue @cezhang 

I will get this fix.

/assign @mikeshng

**Comment by ydFu** [comment]
/close 
Get merged
