### ISSUE TITLE
Describe supported/unsupported K8s distributions

### ISSUE THREAD

**Issue by aii-nozomu-oki** [open-cluster-management-io/open-cluster-management-io.github.io#328]
There are so many K8s distributions that it would be impossible to describe them all.
But I think it is possible to state some things.

- There is probably first class support for kind, K3s, and OpenShift, which is currently [documented](https://open-cluster-management.io/getting-started/installation/register-a-cluster/#bootstrap-a-klusterlet).
As for kind, it appears to be used in e2e testing.

- EKS as a hub is not supported.
https://github.com/open-cluster-management-io/enhancements/issues/68
https://github.com/open-cluster-management-io/registration/issues/185
https://github.com/aws/containers-roadmap/issues/1856

**Comment by mikeshng** [comment]
Thank you @aii-nozomu-oki for reporting this issue.

Would you like to make a contribution to list some of the supported platforms so we can discuss further in the PR?
It's difficult for us to list all the platforms because we will have to maintain the versions and testings as well.

**Comment by aii-nozomu-oki** [comment]
Sure, I have created.
